### ISSUE TITLE
Change default sorting for tarentula commands to: '_score'

### ISSUE THREAD

**Issue by miguelfg** [ICIJ/datashare-tarentula#35]
Datashare tarentula uses by default the '_id' field for sorting, what is triggering the error for the 2 indexes reported. To avoid it, using --sort-by "_score" in the tarentula command fixes it, or overcomes the error.

**Comment by ClemDoum** [comment]
The default ES sort is [by `_score`](https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html#sort-search-results), so removing the `_id` sort will probably do the job

**Comment by miguelfg** [comment]
> The default ES sort is [by `_score`](https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html#sort-search-results), so removing the `_id` sort will probably do the job

Just removing by `_id` wasn't enough, because [the code](https://github.com/ICIJ/datashare-tarentula/blob/903ab79e19d3a11af781154dc726305f7b5d6158/tarentula/datashare_client.py#L179) is expecting the 'sort' key in the response from ES, and when using the default `_score`  it does not return in it.
